#!/usr/bin/env bash
# Acceptance tests for agent-factory-0is (Sync AGENTS.md with CLAUDE.md conventions).
# One test function per acceptance criterion in docs/stories/agent-factory-0is.md - see that
# file and docs/design/agent-factory-0is.md ("Test strategy") for the criteria/commands these
# are derived from. No unit-test framework applies here (this is plain-markdown content, not
# code); this is a plain shell acceptance script, run directly:
#   bash tests/acceptance/agent-factory-0is.sh
# PASS/FAIL is printed per criterion; overall exit is non-zero if any criterion FAILs.
set -uo pipefail

KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$KIT_DIR"

pass=0
fail=0

ok()  { echo "PASS: $1"; pass=$((pass+1)); }
bad() { echo "FAIL: $1"; fail=$((fail+1)); }

# AC3 fixture: the Codex-only block, byte-for-byte, as it existed before this story (and must
# remain unchanged after it). Captured from AGENTS.md at story start (2026-09-23).
read -r -d '' CODEX_BLOCK_EXPECTED <<'CODEXEOF'
<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->
## Beads Issue Tracker

Use Beads (`bd`) for durable task tracking in repositories that include it. Use the `beads` skill at `.agents/skills/beads/SKILL.md` (project install) or `~/.agents/skills/beads/SKILL.md` (global install) for Beads workflow guidance, then use the `bd` CLI for issue operations.

### Quick Reference

```bash
bd ready                # Find available work
bd show <id>            # View issue details
bd update <id> --claim  # Claim work
bd close <id>           # Complete work
bd prime                # Refresh Beads context
```

### Rules

- Use `bd` for all task tracking; do not create markdown TODO lists.
- Run `bd prime` when Beads context is missing or stale. Codex 0.129.0+ can load Beads context automatically through native hooks; use `/hooks` to inspect or toggle them.
- Keep persistent project memory in Beads via `bd remember`; do not create ad hoc memory files.

**Architecture in one line:** issues live in a local Dolt DB; sync uses `refs/dolt/data` on your git remote; `.beads/issues.jsonl` is a passive export. See https://github.com/gastownhall/beads/blob/main/docs/core-concepts/sync-concepts.md for details and anti-patterns.
<!-- END BEADS CODEX SETUP -->
CODEXEOF

# AC1: root AGENTS.md contains the same project-conventions content as root CLAUDE.md (the
# header through the Definition-of-done section, i.e. everything above the "BEGIN BEADS
# INTEGRATION" marker in CLAUDE.md) - and the old "Agent Instructions" intro / "Non-Interactive
# Shell Commands" section are gone.
test_ac1_shared_conventions_present() {
  local claude_pre agents_pre
  claude_pre=$(sed -n '1,/<!-- BEGIN BEADS INTEGRATION/p' CLAUDE.md | sed '$d')
  agents_pre=$(sed -n '1,/<!-- BEGIN BEADS INTEGRATION/p' AGENTS.md | sed '$d')
  if [ "$claude_pre" != "$agents_pre" ]; then
    bad "ac1: AGENTS.md content above 'BEGIN BEADS INTEGRATION' does not match CLAUDE.md's"
    return
  fi
  if grep -q '^# Agent Instructions' AGENTS.md; then
    bad "ac1: AGENTS.md still has the old '# Agent Instructions' intro"
    return
  fi
  if grep -q 'Non-Interactive Shell Commands' AGENTS.md; then
    bad "ac1: AGENTS.md still has the old 'Non-Interactive Shell Commands' section"
    return
  fi
  ok "ac1: AGENTS.md shares CLAUDE.md's project-conventions content; old intro/section are gone"
}

# AC2: the "BEGIN BEADS INTEGRATION" / "END BEADS INTEGRATION" managed block content matches
# between AGENTS.md and CLAUDE.md.
test_ac2_managed_block_matches() {
  local claude_block agents_block
  claude_block=$(sed -n '/<!-- BEGIN BEADS INTEGRATION/,/<!-- END BEADS INTEGRATION -->/p' CLAUDE.md)
  agents_block=$(sed -n '/<!-- BEGIN BEADS INTEGRATION/,/<!-- END BEADS INTEGRATION -->/p' AGENTS.md)
  if [ -z "$claude_block" ]; then
    bad "ac2: CLAUDE.md has no BEGIN/END BEADS INTEGRATION block to compare against"
    return
  fi
  if [ "$claude_block" != "$agents_block" ]; then
    bad "ac2: AGENTS.md's BEADS INTEGRATION managed block does not match CLAUDE.md's"
    return
  fi
  ok "ac2: BEADS INTEGRATION managed block matches between AGENTS.md and CLAUDE.md"
}

# AC3: the "BEGIN BEADS CODEX SETUP" / "END BEADS CODEX SETUP" block in AGENTS.md is preserved
# unchanged (byte-for-byte) from before this story, and is present.
test_ac3_codex_block_preserved() {
  if ! grep -q '<!-- BEGIN BEADS CODEX SETUP' AGENTS.md; then
    bad "ac3: AGENTS.md is missing the BEGIN BEADS CODEX SETUP block"
    return
  fi
  local agents_codex_block
  agents_codex_block=$(sed -n '/<!-- BEGIN BEADS CODEX SETUP/,/<!-- END BEADS CODEX SETUP -->/p' AGENTS.md)
  if [ "$agents_codex_block" != "$CODEX_BLOCK_EXPECTED" ]; then
    bad "ac3: AGENTS.md's BEADS CODEX SETUP block differs from its pre-story content"
    return
  fi
  ok "ac3: AGENTS.md's BEADS CODEX SETUP block is present and byte-for-byte unchanged"
}

# AC4: `diff AGENTS.md CLAUDE.md` at repo root - the only remaining difference is the
# Codex-specific block from AC3 (no drift elsewhere in shared conventions or Beads-integration
# content).
test_ac4_diff_only_codex_block() {
  local d
  d=$(diff AGENTS.md CLAUDE.md)
  if [ -z "$d" ]; then
    bad "ac4: diff AGENTS.md CLAUDE.md shows no difference at all - expected the Codex block to still differ"
    return
  fi
  # Every added line (AGENTS.md-only, '<' prefixed) must belong to the Codex block or be part of
  # the diff hunk framing (no '>' lines from CLAUDE.md allowed at all - CLAUDE.md has no unique
  # content once AC1/AC2 hold).
  if grep -E '^>' <<<"$d" >/dev/null; then
    bad "ac4: diff AGENTS.md CLAUDE.md has lines unique to CLAUDE.md - AGENTS.md is missing shared content"
    return
  fi
  local non_codex_lines
  non_codex_lines=$(grep -E '^< ' <<<"$d" | sed -E 's/^< //' | grep -vFxf <(printf '%s\n' "$CODEX_BLOCK_EXPECTED") | grep -v '^$')
  if [ -n "$non_codex_lines" ]; then
    bad "ac4: diff AGENTS.md CLAUDE.md has extra AGENTS.md-only lines outside the Codex block: $non_codex_lines"
    return
  fi
  ok "ac4: diff AGENTS.md CLAUDE.md differs only by the Codex-specific block"
}

test_ac1_shared_conventions_present
test_ac2_managed_block_matches
test_ac3_codex_block_preserved
test_ac4_diff_only_codex_block

echo "---"
echo "pass=$pass fail=$fail"
[ "$fail" -eq 0 ]
